# encoding: UTF-8
#
# =================================================================
# Licensed Materials - Property of IBM
#
# Copyright 2015, 2016 IBM Corp.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# =================================================================
#

# Set to some text value if you want templated config files
# to contain a custom banner at the top of the written file
default['ibm-openstack']['zvm-driver']['custom_template_banner'] = '
# This file autogenerated by Chef
# Do not edit, changes will be overwritten
'

# nova configuration for optimization
# The memory overcommit ratio for the z/VM Driver. The recommended value is 3.
default['ibm-openstack']['zvm-driver']['config']['ram_allocation_ratio'] = 3
# Live migration will not succeed with the default value, so set it to 180 seconds.
default['ibm-openstack']['zvm-driver']['rpc_response_timeout'] = 180

# ceilometer configuration for optimization
# Interval of ceilometer cached data update.
default['ibm-openstack']['zvm-driver']['cache_update_interval'] = 600
